version: '2.1'
services:
  rabbitmq_master:
    build: 
      context: ./rabbitmq
    container_name: rabbitmq_master
    hostname: "rabbitmq_master"
    environment:
      RABBITMQ_ERLANG_COOKIE: abcdefg
      CLUSTERED: "true"
      VIRTUAL_HOST: rabbitmq-master.com.br
      VIRTUAL_PORT: 15672
    volumes:
      - "./storage/master:/var/lib/rabbitmq"
    network_mode: "bridge"
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"

  export_master_metrics:
    image: kbudde/rabbitmq-exporter
    container_name: export_master_metrics
    hostname: export_master_metrics
    environment:
      RABBIT_URL: "http://rabbitmq_master:15672"
      RABBIT_USER: "admin"
      RABBIT_PASSWORD: "admin"
      PUBLISH_PORT: "9419"
      RABBIT_CAPABILITIES: "bert,no_sort"
      RABBIT_EXPORTERS: "node,overview,queue" 
    network_mode: "bridge"
    links:
      - rabbitmq_master

  rabbitmq_slave:
    build: 
      context: ./rabbitmq
    container_name: rabbitmq_slave
    hostname: "rabbitmq_slave"
    environment:
      RABBITMQ_ERLANG_COOKIE: abcdefg
      CLUSTERED: "true"
      VIRTUAL_HOST: rabbitmq-slave.com.br
      VIRTUAL_PORT: 15672
    volumes:
      - "./storage/slave:/var/lib/rabbitmq"
    network_mode: "bridge"
    links:
      - rabbitmq_master
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"

  export_slave_metrics:
    image: kbudde/rabbitmq-exporter
    container_name: export_slave_metrics
    hostname: export_slave_metrics
    environment:
      RABBIT_URL: "http://rabbitmq_slave:15672"
      RABBIT_USER: "admin"
      RABBIT_PASSWORD: "admin"
      PUBLISH_PORT: "9419"
      RABBIT_CAPABILITIES: "bert,no_sort"
      RABBIT_EXPORTERS: "node,overview,queue" 
    network_mode: "bridge"
    links:
      - rabbitmq_slave
 
  haproxy:
    build: 
      context: ./haproxy
    container_name: haproxy
    hostname: haproxy
    ports:
      - 15672:15672
      - 9419:9419
      - 5672:5672
      - 20000:20000
    network_mode: "bridge"
    links:
      - rabbitmq_master
      - rabbitmq_slave
      - export_master_metrics
      - export_slave_metrics

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    network_mode: "host"
    volumes:
       - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
          
  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: "host"
    ports:
      - 3000:3000
    environment:
      ADMIN_USER: "admin"
      ADMIN_PASSWORD: "admin"

