global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 10s
  external_labels:
      monitor: 'rabbit-monitor'

rule_files:
scrape_configs:
  
  - job_name: 'Rabbit'
    scrape_interval: 59s
    scrape_timeout: 59s
    metrics_path: /metrics
    static_configs:
      - targets: 
        - localhost:9419
