global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'rabbit-monitor'

rule_files:
scrape_configs:
  
  - job_name: 'Rabbit'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['localhost:15672']
